name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: jaelkalvin
        uses: docker/login-action@v3
        with:
          username: jaelkalvin
          password: dckr_pat_Y7EfQrfzeIRlmZjG0Zg6neOLzA4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: jaelkalvin/${{ github.event.repository.name }}:latest
